In [1]:
import pandas as pd
import numpy as np

## 2.1 Разбиение набора данных

In [2]:
df=pd.read_csv('result_data.csv')

Разобъём набор данных таким образом, как это рекомендовано согласно документации `Sklearn`. А именно `30 на 70`. Как представленно в описании, такая выборка является оптимальной, поскольку абсолютное большинство данных должно находится при обучении модели, чтобы получить наиболее оптимизированную модель со стороны её точности

### Стратификация
При разделении стратифицируем данные, чтобы получить одинаковую в процентом соотношении выборку, чтобы не было перевеса на какой-то один класс и такая ситуация не повлияла на некорректное обучение модели

In [3]:
df

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million,mean_new_cases,mean_new_deaths,Rt
0,MEX,North America,Mexico,2022-05-12,5745652.0,0.0,853.143,324465.0,0.0,18.714,...,1.38,75.05,0.779,0.0,0.0,0.0,0.0,6612.46092,365.025287,inf
1,MEX,North America,Mexico,2022-05-13,5745652.0,0.0,853.143,324465.0,0.0,18.714,...,1.38,75.05,0.779,0.0,0.0,0.0,0.0,6612.46092,365.025287,inf
2,MEX,North America,Mexico,2022-05-14,5745652.0,0.0,853.143,324465.0,0.0,18.714,...,1.38,75.05,0.779,0.0,0.0,0.0,0.0,6612.46092,365.025287,inf
3,MEX,North America,Mexico,2022-05-15,5745652.0,0.0,853.143,324465.0,0.0,18.714,...,1.38,75.05,0.779,0.0,0.0,0.0,0.0,6612.46092,365.025287,inf
4,MEX,North America,Mexico,2022-05-16,5752441.0,6789.0,969.857,324617.0,152.0,21.714,...,1.38,75.05,0.779,0.0,0.0,0.0,0.0,6612.46092,365.025287,inf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187796,PCN,Oceania,Pitcairn,2021-06-16,0.0,0.0,0.000,0.0,0.0,0.000,...,0.00,0.00,0.000,0.0,0.0,0.0,0.0,0.00000,0.000000,0.0
187797,PCN,Oceania,Pitcairn,2021-06-17,0.0,0.0,0.000,0.0,0.0,0.000,...,0.00,0.00,0.000,0.0,0.0,0.0,0.0,0.00000,0.000000,0.0
187798,PCN,Oceania,Pitcairn,2021-06-18,0.0,0.0,0.000,0.0,0.0,0.000,...,0.00,0.00,0.000,0.0,0.0,0.0,0.0,0.00000,0.000000,0.0
187799,PCN,Oceania,Pitcairn,2021-06-19,0.0,0.0,0.000,0.0,0.0,0.000,...,0.00,0.00,0.000,0.0,0.0,0.0,0.0,0.00000,0.000000,0.0
187800,ESH,Africa,Western Sahara,2022-04-20,0.0,0.0,0.000,0.0,0.0,0.000,...,0.00,70.26,0.000,0.0,0.0,0.0,0.0,0.00000,0.000000,0.0

In [4]:
f.replace([np.inf, -np.inf], np.nan, inplace=True)

NameError: name 'f' is not defined

In [ ]:
df=df[df['Rt']<5].reset_index(drop=True)

## Определение переменной опасности

In [ ]:
df1=df[df['Rt']<=0.7]
df1['Danger']=0

In [ ]:
df2=df[(df['Rt']>0.7) & (df['Rt']<=0.95)]
df2['Danger']=1

In [5]:
df3=df[df['Rt']>0.95]
df3['Danger']=2

C:\Users\slava\AppData\Local\Temp/ipykernel_9456/132883819.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['Danger']=2

In [6]:
df=pd.concat([df1, df2, df3]).reset_index(drop=True)

NameError: name 'df1' is not defined

In [ ]:
X=df[['new_cases', 'new_deaths', 'Rt']]
y=df['Danger']

In [7]:
#Получение выборок #Getting samples
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42, stratify=df['location'])

NameError: name 'X' is not defined

## 2.3 Классифиткация 

Рассмотрим три модели классификации
### KNeighborsClassifier
Классификация на основе соседей - это тип обучения на основе экземпляров или необобщающего обучения: он не пытается построить общую внутреннюю модель, а просто сохраняет экземпляры обучающих данных. Классификация вычисляется простым большинством голосов ближайших соседей каждой точки: точке запроса назначается класс данных, который имеет наибольшее количество представителей среди ближайших соседей точки.

### RandomForestClassifier
Случайный лес — это метаоценка, которая соответствует ряду классификаторов дерева решений для различных подвыборок набора данных и использует усреднение для повышения точности прогнозирования и контроля переобучения. Размер подвыборки управляется параметром max_samples, если bootstrap=True (по умолчанию), в противном случае для построения каждого дерева используется весь набор данных
### GaussianNB
Наи́вный ба́йесовский классифика́тор — простой вероятностный классификатор, основанный на применении теоремы Байеса со строгими (наивными) предположениями о независимости. В зависимости от точной природы вероятностной модели, наивные байесовские классификаторы могут обучаться очень эффективно

## Матрикики
Рассмотрим две метрикики для оценивания модели классификации

### accuracy f1-score
Это гармоническое среднее значений точности и полноты. Возьмём её, потому что она дает лучшую оценку неправильно классифицированных случаев

### macro avg f1-score

macro avg f1-score пожалуй, самый простой из многочисленных методов усреднения. Макроусредненная оценка F1 (или макрооценка F1) вычисляется путем взятия среднего арифметического (также известного как невзвешенное среднее) всех оценок F1 для каждого класса. Этот метод будет взят, поскольку он обрабатывает все классы одинаково, независимо от их значений поддержки

## 2.4 Обучение

In [ ]:
#Импорт моделей #Importing models
from sklearn.metrics import classification_report
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB

In [ ]:
#Обучение #Training
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X_train, y_train)
preds=neigh.predict(X_test)
print(classification_report(preds, y_test))

In [ ]:
#Обучение
rfc = RandomForestClassifier()
rfc.fit(X_train, y_train)
rfc_preds=rfc.predict(X_test)
print(classification_report(rfc_preds, y_test))

In [ ]:
#Обучение
gnb = GaussianNB()
gnb.fit(X_train, y_train)
gnb_preds=gnb.predict(X_test)
print(classification_report(gnb_preds, y_test))

### Вывод
Наиболее оптимальной моделью будет `KNeighborsClassifier` c accuracy f1-score = `0.78` и macro avg f1-score = `0.74`, поскольку по сравнению с другими он показал наилучший результат. `RandomForestClassifier` не будет взят, поскольку у него явное переобучение

## Отчёт
* 2.1 Разбиение набора данных - набор данныхз разбит на обучаюшую и тестовую выборки
* 2.3 Классификация - выбраны 3 алгоритма классификации
* 2.4 Обучение - произведена классификация по уровню опасности

In [ ]:
# Сохранение данных # Saving data
df.to_csv('result_data.csv', encoding='utf-8-sig', index=False)